### ISSUE TITLE
Incorrect password comparaison

### ISSUE THREAD

**Issue by etellier** [rito2k/MTR#2]
Hi, in function rebootMTR : password is case sensitive so use "-cne" not "-ne".

if ($pwd1 -ne $pwd2)  =>  if ($pwd1 -**c**ne $pwd2)     Or test is not true if $pwd1= "Password"  and  $pwd2 ="password"

**Comment by rito2k** [comment]
Did not see any problems so far, but thanks for pointing that out! Update has been committed, thanks for your collab ^_^
